import pandas as pd
import numpy as np

print("=" * 70)
print("FINAL EXPERIMENTAL SUMMARY")
print("=" * 70)
print()

# dataset
print("TABLE 1: DATASET COMPOSITION")
print("-" * 70)
combined = pd.read_csv("combined_index.csv")
analysis = pd.read_csv("combined_analysis_set.csv")
print(f"Sampled (after 4001 filter):      {len(combined)}")
print(f"Downloaded and parsed:            {int((combined['status']=='ok').sum())}")
print(f"Valid PX4 with band:              {int(combined['band'].notna().sum())}")
print(f"Gate 1 survivors:                 2168")
print(f"Analysis set:                     {len(analysis)}")
print()

# split
print("TABLE 2: A/B/C SPLIT")
print("-" * 70)
groups = pd.read_csv("analysis_set_with_scores.csv")
print(pd.crosstab(groups["band"], groups["group"]))
print()

# coverage
print("TABLE 3: COVERAGE PER METHOD (nominal = 0.95)")
print("-" * 70)
cov = pd.read_csv("track_b_v3_coverage.csv")
print(cov.round(4).to_string(index=False))
print()
print("Track A per-ratio mean coverage: 0.9521")
print()

# per ratio detection power
print("TABLE 4: PER-RATIO DETECTION POWER")
print("-" * 70)
pr = pd.read_csv("per_ratio_detection_power.csv")
print(pr.round(4).to_string(index=False))
print()

# detection power on combined set
print("TABLE 5: DETECTION POWER (Group C) - Track B v3 (combined 1627 set)")
print("-" * 70)
print("  IsoForest:   n>=2: 13/94, n>=3: 5/24, n>=4: 2/11")
print("  SVM:         n>=2: 14/94, n>=3: 4/24, n>=4: 3/11")
print("  Autoencoder: n>=2: 15/94, n>=3: 4/24, n>=4: 2/11")
print()

# coverage power curve
print("TABLE 6: DETECTION POWER AT COVERAGE = 0.95 (n_indicators >= 2)")
print("-" * 70)
cpc = pd.read_csv("coverage_power_curve.csv")
near = cpc[cpc["coverage"].between(0.94, 0.96)]
print(near.groupby("method")["power_n2"].mean().round(4).to_string())
print()

# case study
print("TABLE 7: TOP 5 HIGH-ANOMALY LOGS (Group C)")
print("-" * 70)
cs = pd.read_csv("case_study_top15.csv")
print(cs.head(5)[["log_id", "band", "n_indicators", "sat_frac", "sat_max_run_s"]].to_string(index=False))
print()

print("=" * 70)
print("KEY NUMBERS FOR THE PAPER")
print("=" * 70)
print()
print("Corpus: 2,770 sampled -> 2,168 Gate 1 -> 1,627 analysis set")
print("Split: 325 A, 650 B, 652 C (20/40/40 within band)")
print("Ratios: 10 universal")
print("Score: 95th percentile per ratio, log-transformed")
print()
print("Coverage (alpha=0.05):")
print("  Track A:      0.9521")
print("  IsoForest:    0.9509")
print("  SVM:          0.9463")
print("  Autoencoder:  0.9417")
print()
print("Detection power at coverage=0.95 (n_indicators>=2):")
print("  Autoencoder:  0.1543")
print("  OneClassSVM:  0.1489")
print("  IsoForest:    0.1330")
print("  Track A:      0.0426")
print()
print("Detection power at n_indicators>=3:")
print("  IsoForest:    5/24")
print("  SVM:          4/24")
print("  Autoencoder:  4/24")
print()
print("Detection power at n_indicators>=4:")
print("  SVM:          3/11  (best)")
print("  IsoForest:    2/11")
print("  Autoencoder:  2/11")
print()
print("Best single ratio: baro_vpos (0.1485 at n>=2, 0.2800 at n>=3)")
print("Weakest single ratio: heading (0.0594 at n>=2, 0.0800 at n>=3)")
print()
print("Band-level coverage: v1.12-1.13 = 0.9542, v1.14-1.15 = 0.9669, v1.16+ = 0.9344")
print("  -> v1.16+ under-covers by 1.5 pp (marginal guarantee holds, conditional does not)")